/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ThucHanhBuoi3;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class DVXK extends javax.swing.JFrame {

    /**
     * Creates new form DVXK
     */
    public DVXK() {
        initComponents();
        setTitle("Đặt vé xe khách");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_stt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_hovaten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdb_nam = new javax.swing.JRadioButton();
        rdb_nu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cbb_dotuoi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diachi = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txt_dienthoai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbb_tuyenduong = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbb_giokhoihanh = new javax.swing.JComboBox<>();
        btn_datVe = new javax.swing.JButton();
        btn_huyBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("STT");

        txt_stt.setText("1");

        jLabel2.setText("Họ và tên");

        txt_hovaten.setText("Lê Minh Thắng");
        txt_hovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hovatenActionPerformed(evt);
            }
        });

        jLabel3.setText("Giới tinh");

        buttonGroup1.add(rdb_nam);
        rdb_nam.setSelected(true);
        rdb_nam.setText("Nam");

        buttonGroup1.add(rdb_nu);
        rdb_nu.setText("Nữ");

        jLabel4.setText("Độ tuổi");

        cbb_dotuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dưới 20", "20-30", "30-40", "Trên 40" }));

        jLabel5.setText("Địa chỉ");

        txt_diachi.setColumns(20);
        txt_diachi.setRows(5);
        txt_diachi.setText("Thới Lai - Cần Thơ");
        jScrollPane1.setViewportView(txt_diachi);

        jLabel6.setText("Điện thoại");

        txt_dienthoai.setText("0869859434");

        jLabel7.setText("Tuyến đường");

        cbb_tuyenduong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cần Thơ - Châu Đốc", "Cần Thơ - Sài Gòn" }));

        jLabel8.setText("Giời khởi hành");

        cbb_giokhoihanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3:45", "6:30" }));

        btn_datVe.setText("Đặt vé");
        btn_datVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datVeActionPerformed(evt);
            }
        });

        btn_huyBo.setText("Hủy bỏ");
        btn_huyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_dotuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbb_tuyenduong, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_dienthoai, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbb_giokhoihanh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_datVe)
                        .addGap(28, 28, 28)
                        .addComponent(btn_huyBo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_stt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(txt_hovaten, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_stt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdb_nam)
                    .addComponent(rdb_nu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbb_dotuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_dienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbb_tuyenduong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbb_giokhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_datVe)
                    .addComponent(btn_huyBo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hovatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hovatenActionPerformed

    private void btn_huyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyBoActionPerformed
        // TODO add your handling code here:
        txt_stt.setText("");
        txt_hovaten.setText("");
        txt_diachi.setText("");
        txt_dienthoai.setText("");
    }//GEN-LAST:event_btn_huyBoActionPerformed

    public boolean isNumberic(String stt) {
        if (stt == null) {
            return false;
        }
        try {
            float sothutu = Float.parseFloat(stt);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    private void btn_datVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datVeActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (!isNumberic(txt_stt.getText())) {
            sb.append("STT phải là số!\n");
            txt_stt.setBackground(Color.red);
        } else {
            txt_stt.setBackground(Color.white);
        }

        if (txt_hovaten.getText().equals("")) {
            sb.append("Họ và tên không được rỗng!\n");
            txt_hovaten.setBackground(Color.red);
        } else {
            txt_hovaten.setBackground(Color.white);
        }

        if (txt_dienthoai.getText().equals("")) {
            sb.append("Số điện thoại không được rỗng!\n");
            txt_dienthoai.setBackground(Color.red);
        } else {
            txt_dienthoai.setBackground(Color.white);
        }

        if (txt_diachi.getText().equals("")) {
            sb.append("Địa chỉ không được rỗng!\n");
            txt_diachi.setBackground(Color.red);
        } else {
            txt_diachi.setBackground(Color.white);
        }
        // hiển thị lỗi nhập liệu
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(rootPane, sb);
            return;
        }

        StringBuilder sb2 = new StringBuilder();
        sb2.append("STT: " + txt_stt.getText() + "\n");
        sb2.append("Họ và tên: " + txt_hovaten.getText() + "\n");

        if (rdb_nam.isSelected()) {
            sb2.append("Giới tính: Nam \n");
        } else {
            sb2.append("Giới tính: Nữ \n");
        }

        sb2.append("Độ tuổi: " + cbb_dotuoi.getSelectedItem().toString() + "\n");
        sb2.append("Địa chỉ: " + txt_diachi.getText() + "\n");
        sb2.append("Số điện thoại: " + txt_dienthoai.getText() + "\n");

        sb2.append("Tuyến đường: " + cbb_tuyenduong.getSelectedItem().toString() + "\n");
        sb2.append("Giờ khởi hành: " + cbb_giokhoihanh.getSelectedItem().toString() + "\n");
        
        JOptionPane.showMessageDialog(rootPane, sb2);


    }//GEN-LAST:event_btn_datVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVXK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVXK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVXK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVXK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DVXK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datVe;
    private javax.swing.JButton btn_huyBo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_dotuoi;
    private javax.swing.JComboBox<String> cbb_giokhoihanh;
    private javax.swing.JComboBox<String> cbb_tuyenduong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_nam;
    private javax.swing.JRadioButton rdb_nu;
    private javax.swing.JTextArea txt_diachi;
    private javax.swing.JTextField txt_dienthoai;
    private javax.swing.JTextField txt_hovaten;
    private javax.swing.JTextField txt_stt;
    // End of variables declaration//GEN-END:variables
}
