/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ThucHanhBuoi3;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class KSPM extends javax.swing.JFrame {

    /**
     * Creates new form KSPM
     */
    public KSPM() {
        initComponents();
        setTitle("Khách sạn Phương Nam");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_dongy = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        txt_sohoadon = new javax.swing.JTextField();
        txt_makhachhang = new javax.swing.JTextField();
        txt_tenkhachhang = new javax.swing.JTextField();
        txt_socmnd = new javax.swing.JTextField();
        cbb_sophong = new javax.swing.JComboBox<>();
        txt_sotientt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bảng thanh toán");

        jLabel2.setText("Số hóa đơn");

        jLabel3.setText("Mã khách hàng");

        jLabel4.setText("Tên khách hàng");

        jLabel5.setText("Số CMND");

        jLabel6.setText("Số phòng");

        jLabel7.setText("Số tiền thanh toán");

        btn_dongy.setText("Đồng ý");
        btn_dongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongyActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy bỏ");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        txt_sohoadon.setText("1234");
        txt_sohoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sohoadonActionPerformed(evt);
            }
        });

        txt_makhachhang.setText("PN-1234");

        txt_tenkhachhang.setText("Lê Minh Thắng");

        txt_socmnd.setText("092201005");

        cbb_sophong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "201", "301" }));

        txt_sotientt.setText("200000");
        txt_sotientt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sotienttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btn_dongy)
                        .addGap(39, 39, 39)
                        .addComponent(btn_huy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_sophong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sotientt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_socmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_makhachhang)
                                .addComponent(txt_sohoadon)
                                .addComponent(txt_tenkhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_sohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txt_makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_socmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_sophong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_sotientt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dongy)
                    .addComponent(btn_huy))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        txt_makhachhang.setText("");
        txt_socmnd.setText("");
        txt_sohoadon.setText("");
        txt_sotientt.setText("");
        txt_tenkhachhang.setText("");
    }//GEN-LAST:event_btn_huyActionPerformed

    public boolean KiemTraLaSo(String sotienthanhtoan) {
        if (sotienthanhtoan == null) {
            return false;
        }
        try {
            float sotien = Float.parseFloat(sotienthanhtoan);
        } catch (Exception e) {
            return false;
        }
        return true;
    }

    public boolean KiemTraSoHoaDon(String txt_field) {
        String soNguyen = "\\d{4}";
        boolean flag = txt_field.matches(soNguyen);
        if (!flag) {
            return false;
        }
        return true;
    }

    public boolean KiemTraMaKhachHang(String txt_field) {
        String maKH = "PN-\\d{4}";
        boolean flag = txt_field.matches(maKH);
        if (!flag) {
            return false;
        }
        return true;
    }

    public boolean KiemTraSoCMND(String txt_field) {
        String soCMND = "\\d{9}";
        boolean flag = txt_field.matches(soCMND);
        if (!flag) {
            return false;
        }
        return true;
    }

    private void btn_dongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongyActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (!KiemTraLaSo(txt_sotientt.getText())) {
            sb.append("Số tiền thanh toán phải là số! \n");
            txt_sotientt.setBackground(Color.red);
        } else {
            txt_sotientt.setBackground(Color.white);
        }

        if (!KiemTraSoHoaDon(txt_sohoadon.getText())) {
            sb.append("Số hóa đơn phải là 4 chữ số! \n");
            txt_sohoadon.setBackground(Color.red);
        } else {
            txt_sohoadon.setBackground(Color.white);
        }

        if (!KiemTraMaKhachHang(txt_makhachhang.getText())) {
            sb.append("Mã khách hàng định dạng PN-XXXX (X là chữ số) \n");
            txt_makhachhang.setBackground(Color.red);
        } else {
            txt_makhachhang.setBackground(Color.white);
        }

        if (txt_tenkhachhang.getText().equals("")) {
            sb.append("Tên khách hàng bắt buộc nhập \n");
            txt_tenkhachhang.setBackground(Color.red);
        } else {
            txt_tenkhachhang.setBackground(Color.white);
        }

        if (!KiemTraSoCMND(txt_socmnd.getText())) {
            sb.append("Số CMND: yêu cầu nhập 9 chữ số \n");
            txt_socmnd.setBackground(Color.red);
        } else {
            txt_socmnd.setBackground(Color.white);
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(rootPane, sb);
            return;
        }
        
        StringBuilder sb2 = new StringBuilder();
        sb2.append("Số hóa dơn: " +txt_sohoadon.getText()+ "\n");
         sb2.append("Mã khách hàng: " +txt_makhachhang.getText()+ "\n");
          sb2.append("Tên khách hàng: " +txt_tenkhachhang.getText()+ "\n");
           sb2.append("Số CMND: " +txt_socmnd.getText()+ "\n");
            sb2.append("Số phòng: " +cbb_sophong.getSelectedItem()+ "\n");
             sb2.append("Số tiền thanh toán: " +txt_sotientt.getText()+ "\n");
                 JOptionPane.showMessageDialog(rootPane, sb2);
             


    }//GEN-LAST:event_btn_dongyActionPerformed

    private void txt_sohoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sohoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sohoadonActionPerformed

    private void txt_sotienttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sotienttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sotienttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KSPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KSPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KSPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KSPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KSPM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dongy;
    private javax.swing.JButton btn_huy;
    private javax.swing.JComboBox<String> cbb_sophong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_makhachhang;
    private javax.swing.JTextField txt_socmnd;
    private javax.swing.JTextField txt_sohoadon;
    private javax.swing.JTextField txt_sotientt;
    private javax.swing.JTextField txt_tenkhachhang;
    // End of variables declaration//GEN-END:variables
}
